### PR TITLE
Round ltv values to 3 decimal places

### PR DESCRIPTION
**Pull request by fna**
just what it says, Travis couldn't find any errors either

### CODE REVIEW

**Comment by amymok** [comment]
@fna Are we also changing the database field to Decimal instead of Float?

**Comment by fna** [comment]
I haven't done it, but it does make sense if we're only interested in the 3 decimal points. I'll update this branch.

**Comment by amymok** [comment]
@fna 

calculate_loan_to_value in views.py needs to be updated to convert float to string to decimal, since it is outputting a float, and try to do a comparison with decimal in the database.  It crashes.

**Comment by fna** [comment]
@amymok excellent find, but I can't recreate it, could you describe the steps?

**Comment by amymok** [comment]
looks great :+1:

**Pull request merged**
