### PR TITLE
Fix OaH API performance problem

### PR DESCRIPTION
**Pull request by fna**
@amymok give it a run on local box, I got 4-6x faster execution, but sometimes it runs just as slow as before and I can't yet figure out what's causing it

### CODE REVIEW

**Comment by amymok** [comment]
Ran them, but never 4x - 6x faster.  Something like 11ms vs 17ms at most.  But now it seems slower than original.  I mean I can merge, but not sure if this is helping much.

**Comment by fna** [comment]
@amymok don't yet merge.

How does it feel slower? 

On my local the whole run used to take about 120ms, now it's around 25ms (according to debug module). I didn't change any MySQL configs.

**Comment by amymok** [comment]
Mine was never that long unless the very first query.

**Comment by fna** [comment]
ok, I'll spend more time with it tomorrow; can't think of an easy way to test it in build

**Pull request merged**
