### PR TITLE
Issue #78: Fix urls

### PR DESCRIPTION
**Pull request by amymok**
This pull request is to address issue https://github.com/cfpb/owning-a-home-api/issues/78

An issue was identified on the routing of mortgage insurance URLs.

If one entered any character between the routes and parameters, the URLs will just simply ignored these characters and do the proper routings as if these were not existed. i.e.
build.consumerfinance.gov/oah-api/mortgage-insurance/dereare?price=2343566&.....
vs.
build.consumerfinance.gov/oah-api/mortgage-insurance/?price=2343566&.....

The appropriate behavior for the one with additional characters should returned a 404. So this pull request will route this request to 404.

We also found that county limits also have the same issue, so this is being fixed together.

### CODE REVIEW

**Comment by fna** [comment]
@amymok This looks awfully similar to https://github.com/cfpb/owning-a-home-api/pull/82. Does it include it?

**Comment by amymok** [comment]
@fna Yes, I guess branch from #81 , since I didn't want to revert my oah-api urls to add this branch.  But if there's an issue, I can pull out to do this change.

**Comment by fna** [comment]
No worries, just delete the other PR

**Comment by fna** [comment]
Looks good, merging

**Pull request merged**
